version: "3.7"

services:

  # app:
  #   image: node:alpine
  #   # container_name: app-container
  #   working_dir: /usr/app
  #   command: npm run compose_dev
  #   volumes:
  #     - .:/usr/app
  #     - /usr/app/node_modules
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   #Start this service only after this dependency is OK:
  #   depends_on:
  #     pg-db:
  #       condition: service_healthy

  pg-db:
    image: postgres
    # container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_HOST: ${POSTGRES_HOST}   #Docker service uses a default value for this field
      # POSTGRES_PORT: ${POSTGRES_PORT}   #Docker service uses a default value for this field
      POSTGRES_DB: ${POSTGRES_DB}
    #Data saved outside the Docker container, on my local PC - add this dir to the .gitignore / .dockerignore files:
    volumes:
       - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    #Check if this service is OK:
    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    #   timeout: 10s
    #   retries: 5
