version: "3.7"

services:

  # app:
  #   image: node:alpine
  #   ...
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     mysql-db:
  #       condition: service_healthy

  mysql-db:
    image: mysql
    platform: linux/arm64
    # container_name: mysql-container
    #V1 - Map vars one by one, if service vars are not named like ".env" file vars:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_USER: ${MYSQL_USER}          #Docker service uses a default value for this field
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}  #Docker service uses a default value for this field
      # MYSQL_HOST: ${MYSQL_HOST}          #Docker service uses a default value for this field
      # MYSQL_PORT: ${MYSQL_PORT}          #Docker service uses a default value for this field
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    #V2 - Give the service access to the entire ".env" file:
    # env_file:
    #   - .env
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 10s
    #   retries: 5
