version: "3.7"

services:

  mysql-db:
    image: mysql
    # container_name: mysql-container
    #V1 - Map vars one by one, if service vars are not named like ".env" file vars:
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   # ...
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #V2 - Give the service access to the entire ".env" file:
    env_file:
      - .env
    volumes:
      - ./mysql-data:/var/lib/mysql
    #Here, unlike previous examples, the “app” service is running @ localhost, and the “db” service is (the only service) running in the docker container. So, this time I do have to expose (publish) the ports out of the container.
    #Also, I could have added “DATABASE_PORT” @ the .env file, to avoid leaving the port number hardcoded here.
    ports:
    - "3306:3306"
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 10s
    #   retries: 5
