version: "3.7"

services:

  main:
    #Image upon I will build my container. No need to customize image name, else I would have to tell the name of the original image somewhere else.
    image: node:alpine
    #Name of the container. Defaulf value is directory name, or service name.
    # container_name: docker-node
    #Build context = ".": use instructions from Dockerfile (like RUN install, COPY, etc.) to build the image.
    # build: .
    #TODO - Add description
    working_dir: /usr/app
    #Since I'm not using Dockerfile to run "npm install", the command here will have to: 1. install dependencies, and 2. run the app.
    command: npm run start:compose_dev
    #Folders of my local directory the container will have access (give root access to read the package.json file).
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    #This service has native access to the ".env" file. No need of this:
    # env_file:
    #   - .env
    #Or this:
    # environment:
    #   SERVER_PORT: ${SERVER_PORT}
    #But I still have to expose (publish) the containers ports:
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
