version: "3.7"

services:

  app:
    image: python:3
    # container_name: app-container
    build: .
    working_dir: /usr/app
    # command: pip install -r requirements.txt
    command: python src/server.py
    # command: ["pip", "install", "-r", "requirements.txt"]
    # command: ["pip", "install", "-r", "requirements.txt", "python", "server.py"]
    # command: ["pip install -r requirements.txt && python server.py"]
    volumes:
      - .:/usr/app
    ports:
      - "${PORT}:${PORT}"
    # depends_on:
    #   requirements:
    #     condition: service_healthy
    #     condition: service_completed_successfully

  # requirements:
  #   image: python:3
  #   # build: .
  #   working_dir: /usr/app
  #   command: pip install -r requirements.txt
  #   volumes:
  #     - .:/usr/app
